# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GenerateWebMapWithWmts
                                 A QGIS plugin
 Generate web map in Arc GIS Online containing tile services from planet
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-11-23
        copyright            : (C) 2020 by line
        email                : rweber@osmre.gov
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GenerateWebMapWithWmts class from file GenerateWebMapWithWmts.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .agol_qgis_plugin import GenerateWebMapWithWmts
    return GenerateWebMapWithWmts(iface)
